#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com
# -------------------------------------------------------
# Delete line with alias from bashrc
awk '!/ctftoolkit/' ~/.bashrc > temp && mv temp ~/.bashrc
