#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com
# -------------------------------------------------------
# Delete line with alias from bashrc
while read -r ~/.bashrc; do
  [[ ! $s =~ alias 'ctftoolkit'=/usr/share/ctftoolkit/./main/ ]] && echo "$line"
done <~/.bashrc > o 
mv o ~/.bashrc
