#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com
# -------------------------------------------------------
# Check if directory exists, if not, make one.
[ -d "/usr/share/CTFToolkit" ] || mkdir /usr/share/CTFToolkit

# Check for alias in bashrc file if not one then add one
if grep -Fxq "alias 'CTFToolkit'=/usr/share/CTFToolkit/./main" ~/.bashrc
then
    echo "Directory already satisfies needs."
else
    echo "alias 'CTFToolkit'=/usr/share/CTFToolkit/./main" >> ~/.bashrc
fi

# Remove LICENSE and README from Github
rm /usr/share/CTFToolkit/README.md /usr/share/CTFToolkit/LICENSE
