#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com
# -------------------------------------------------------
# Check if directory exists, if not, make one.
[ -d "/usr/share/ctftoolkit" ] || mkdir /usr/share/ctftoolkit

# Check for alias in bashrc file if not one then add one
if grep -Fxq "alias 'ctftoolkit'=/usr/share/ctftoolkit/./main" ~/.bashrc
then
    echo "Alias already satisfied."
else
    echo "alias 'ctftoolkit'=/usr/share/ctftoolkit/./main" >> ~/.bashrc
fi

# Clone everything in the repo into /usr/share/ctftoolkit
echo "Cloning 'CTFToolkit' into /usr/share/ctftoolkit..."
git clone https://github.com/Aaronvigal/CTFToolkit.git /usr/share/ctftoolkit>/dev/null 2>&1

# Remove LICENSE and README from Github
rm /usr/share/ctftoolkit/README.md /usr/share/ctftoolkit/LICENSE>/dev/null 2>&1

# Make file executable
chmod +x /usr/share/ctftoolkit/remove>/dev/null 2>&1
chmod +x /usr/share/ctftoolkit/update>/dev/null 2>&1

# Remove setup and all the .git files
rm /usr/share/ctftoolkit/setup>/dev/null 2>&1
