#!/bin/bash
# Script made by Aaron Vigal. http://www.aaronvigal.com
# -------------------------------------------------------
# Delete directory and all files
cd ~
rm -rf /usr/share/ctftoolkit

# Recreate directory
mkdir /usr/share/ctftoolkit

# Clone everything in the repo into /usr/share/ctftoolkit
echo "Cloning 'CTFToolkit' into /usr/share/ctftoolkit..."
git clone https://github.com/Aaronvigal/CTFToolkit.git /usr/share/ctftoolkit>/dev/null 

# Remove LICENSE and README from Github
rm /usr/share/ctftoolkit/README.md /usr/share/ctftoolkit/LICENSE>/dev/null 

# Make file executable
chmod +x /usr/share/ctftoolkit/remove>/dev/null 
chmod +x /usr/share/ctftoolkit/update>/dev/null 

# Remove setup and all the .git files
rm /usr/share/ctftoolkit/setup>/dev/null 
